FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL_REAL
ARG VITE_API_URL_MOCK
ARG VITE_USE_MOCK

ARG VITE_MS_CATALOGOS_REAL
ARG VITE_MS_CATALOGOS_MOCK
ARG VITE_MS_CATALOGOS_USE_MOCK

ARG VITE_MS_MAPEOS_LINEA_REAL
ARG VITE_MS_MAPEOS_LINEA_MOCK
ARG VITE_MS_MAPEOS_LINEA_USE_MOCK
ARG VITE_MS_MAPEOS_CAMPANA_REAL
ARG VITE_MS_MAPEOS_CAMPANA_MOCK
ARG VITE_MS_MAPEOS_CAMPANA_USE_MOCK

ARG VITE_MS_TAREAS_LINEA_REAL
ARG VITE_MS_TAREAS_LINEA_MOCK
ARG VITE_MS_TAREAS_LINEA_USE_MOCK
ARG VITE_MS_TAREAS_CAMPANA_REAL
ARG VITE_MS_TAREAS_CAMPANA_MOCK
ARG VITE_MS_TAREAS_CAMPANA_USE_MOCK

ARG VITE_MS_COLUMNAS_LINEA_REAL
ARG VITE_MS_COLUMNAS_LINEA_MOCK
ARG VITE_MS_COLUMNAS_LINEA_USE_MOCK
ARG VITE_MS_COLUMNAS_CAMPANA_REAL
ARG VITE_MS_COLUMNAS_CAMPANA_MOCK
ARG VITE_MS_COLUMNAS_CAMPANA_USE_MOCK

ARG VITE_MS_BITACORA_REAL
ARG VITE_MS_BITACORA_MOCK
ARG VITE_MS_BITACORA_USE_MOCK

ARG VITE_MS_HORARIOS_LINEA_REAL
ARG VITE_MS_HORARIOS_LINEA_MOCK
ARG VITE_MS_HORARIOS_LINEA_USE_MOCK
ARG VITE_MS_HORARIOS_CAMPANA_REAL
ARG VITE_MS_HORARIOS_CAMPANA_MOCK
ARG VITE_MS_HORARIOS_CAMPANA_USE_MOCK

ARG VITE_MS_MONITOR_LINEA_REAL
ARG VITE_MS_MONITOR_LINEA_MOCK
ARG VITE_MS_MONITOR_LINEA_USE_MOCK
ARG VITE_MS_MONITOR_CAMPANA_REAL
ARG VITE_MS_MONITOR_CAMPANA_MOCK
ARG VITE_MS_MONITOR_CAMPANA_USE_MOCK

ARG VITE_MS_REPORTES_LINEA_REAL
ARG VITE_MS_REPORTES_LINEA_MOCK
ARG VITE_MS_REPORTES_LINEA_USE_MOCK
ARG VITE_MS_REPORTES_CAMPANA_REAL
ARG VITE_MS_REPORTES_CAMPANA_MOCK
ARG VITE_MS_REPORTES_CAMPANA_USE_MOCK

ARG VITE_MS_REPORTES_ABC_LINEA_REAL
ARG VITE_MS_REPORTES_ABC_LINEA_MOCK
ARG VITE_MS_REPORTES_ABC_LINEA_USE_MOCK
ARG VITE_MS_REPORTES_ABC_CAMPANA_REAL
ARG VITE_MS_REPORTES_ABC_CAMPANA_MOCK
ARG VITE_MS_REPORTES_ABC_CAMPANA_USE_MOCK

ARG VITE_MS_REPORTES_RESPONSYS_LINEA_REAL
ARG VITE_MS_REPORTES_RESPONSYS_LINEA_MOCK
ARG VITE_MS_REPORTES_RESPONSYS_LINEA_USE_MOCK
ARG VITE_MS_REPORTES_RESPONSYS_CAMPANA_REAL
ARG VITE_MS_REPORTES_RESPONSYS_CAMPANA_MOCK
ARG VITE_MS_REPORTES_RESPONSYS_CAMPANA_USE_MOCK

ARG VITE_OKTA_ISSUER
ARG VITE_OKTA_CLIENT_ID
ARG VITE_OKTA_REDIRECT_URI

RUN npm run build


FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD wget -q --spider http://localhost/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
