#!/usr/bin/env bash
set -euo pipefail

IMAGE_NAME="as-ms-ar-abc-frontend"
VERSION="${1:-latest}"
TAG="${IMAGE_NAME}:${VERSION}"
TAR_FILE="${IMAGE_NAME}-${VERSION}.tar"

ENV_FILE="${2:-.env}"
if [[ -f "$ENV_FILE" ]]; then
    echo "Loading variables from $ENV_FILE"
    set -a
    source <(grep -v '^\s*#' "$ENV_FILE" | grep -v '^\s*$')
    set +a
fi

e() { echo "${!1:-}"; }

echo ""
echo "Building image: $TAG"

docker build \
    --build-arg VITE_API_URL_REAL="$(e VITE_API_URL_REAL)" \
    --build-arg VITE_API_URL_MOCK="$(e VITE_API_URL_MOCK)" \
    --build-arg VITE_USE_MOCK="$(e VITE_USE_MOCK)" \
    \
    --build-arg VITE_MS_CATALOGOS_REAL="$(e VITE_MS_CATALOGOS_REAL)" \
    --build-arg VITE_MS_CATALOGOS_MOCK="$(e VITE_MS_CATALOGOS_MOCK)" \
    --build-arg VITE_MS_CATALOGOS_USE_MOCK="$(e VITE_MS_CATALOGOS_USE_MOCK)" \
    \
    --build-arg VITE_MS_MAPEOS_LINEA_REAL="$(e VITE_MS_MAPEOS_LINEA_REAL)" \
    --build-arg VITE_MS_MAPEOS_LINEA_MOCK="$(e VITE_MS_MAPEOS_LINEA_MOCK)" \
    --build-arg VITE_MS_MAPEOS_LINEA_USE_MOCK="$(e VITE_MS_MAPEOS_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_MAPEOS_CAMPANA_REAL="$(e VITE_MS_MAPEOS_CAMPANA_REAL)" \
    --build-arg VITE_MS_MAPEOS_CAMPANA_MOCK="$(e VITE_MS_MAPEOS_CAMPANA_MOCK)" \
    --build-arg VITE_MS_MAPEOS_CAMPANA_USE_MOCK="$(e VITE_MS_MAPEOS_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_TAREAS_LINEA_REAL="$(e VITE_MS_TAREAS_LINEA_REAL)" \
    --build-arg VITE_MS_TAREAS_LINEA_MOCK="$(e VITE_MS_TAREAS_LINEA_MOCK)" \
    --build-arg VITE_MS_TAREAS_LINEA_USE_MOCK="$(e VITE_MS_TAREAS_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_TAREAS_CAMPANA_REAL="$(e VITE_MS_TAREAS_CAMPANA_REAL)" \
    --build-arg VITE_MS_TAREAS_CAMPANA_MOCK="$(e VITE_MS_TAREAS_CAMPANA_MOCK)" \
    --build-arg VITE_MS_TAREAS_CAMPANA_USE_MOCK="$(e VITE_MS_TAREAS_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_COLUMNAS_LINEA_REAL="$(e VITE_MS_COLUMNAS_LINEA_REAL)" \
    --build-arg VITE_MS_COLUMNAS_LINEA_MOCK="$(e VITE_MS_COLUMNAS_LINEA_MOCK)" \
    --build-arg VITE_MS_COLUMNAS_LINEA_USE_MOCK="$(e VITE_MS_COLUMNAS_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_COLUMNAS_CAMPANA_REAL="$(e VITE_MS_COLUMNAS_CAMPANA_REAL)" \
    --build-arg VITE_MS_COLUMNAS_CAMPANA_MOCK="$(e VITE_MS_COLUMNAS_CAMPANA_MOCK)" \
    --build-arg VITE_MS_COLUMNAS_CAMPANA_USE_MOCK="$(e VITE_MS_COLUMNAS_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_BITACORA_REAL="$(e VITE_MS_BITACORA_REAL)" \
    --build-arg VITE_MS_BITACORA_MOCK="$(e VITE_MS_BITACORA_MOCK)" \
    --build-arg VITE_MS_BITACORA_USE_MOCK="$(e VITE_MS_BITACORA_USE_MOCK)" \
    \
    --build-arg VITE_MS_HORARIOS_LINEA_REAL="$(e VITE_MS_HORARIOS_LINEA_REAL)" \
    --build-arg VITE_MS_HORARIOS_LINEA_MOCK="$(e VITE_MS_HORARIOS_LINEA_MOCK)" \
    --build-arg VITE_MS_HORARIOS_LINEA_USE_MOCK="$(e VITE_MS_HORARIOS_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_HORARIOS_CAMPANA_REAL="$(e VITE_MS_HORARIOS_CAMPANA_REAL)" \
    --build-arg VITE_MS_HORARIOS_CAMPANA_MOCK="$(e VITE_MS_HORARIOS_CAMPANA_MOCK)" \
    --build-arg VITE_MS_HORARIOS_CAMPANA_USE_MOCK="$(e VITE_MS_HORARIOS_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_MONITOR_LINEA_REAL="$(e VITE_MS_MONITOR_LINEA_REAL)" \
    --build-arg VITE_MS_MONITOR_LINEA_MOCK="$(e VITE_MS_MONITOR_LINEA_MOCK)" \
    --build-arg VITE_MS_MONITOR_LINEA_USE_MOCK="$(e VITE_MS_MONITOR_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_MONITOR_CAMPANA_REAL="$(e VITE_MS_MONITOR_CAMPANA_REAL)" \
    --build-arg VITE_MS_MONITOR_CAMPANA_MOCK="$(e VITE_MS_MONITOR_CAMPANA_MOCK)" \
    --build-arg VITE_MS_MONITOR_CAMPANA_USE_MOCK="$(e VITE_MS_MONITOR_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_REPORTES_LINEA_REAL="$(e VITE_MS_REPORTES_LINEA_REAL)" \
    --build-arg VITE_MS_REPORTES_LINEA_MOCK="$(e VITE_MS_REPORTES_LINEA_MOCK)" \
    --build-arg VITE_MS_REPORTES_LINEA_USE_MOCK="$(e VITE_MS_REPORTES_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_REPORTES_CAMPANA_REAL="$(e VITE_MS_REPORTES_CAMPANA_REAL)" \
    --build-arg VITE_MS_REPORTES_CAMPANA_MOCK="$(e VITE_MS_REPORTES_CAMPANA_MOCK)" \
    --build-arg VITE_MS_REPORTES_CAMPANA_USE_MOCK="$(e VITE_MS_REPORTES_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_REPORTES_ABC_LINEA_REAL="$(e VITE_MS_REPORTES_ABC_LINEA_REAL)" \
    --build-arg VITE_MS_REPORTES_ABC_LINEA_MOCK="$(e VITE_MS_REPORTES_ABC_LINEA_MOCK)" \
    --build-arg VITE_MS_REPORTES_ABC_LINEA_USE_MOCK="$(e VITE_MS_REPORTES_ABC_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_REPORTES_ABC_CAMPANA_REAL="$(e VITE_MS_REPORTES_ABC_CAMPANA_REAL)" \
    --build-arg VITE_MS_REPORTES_ABC_CAMPANA_MOCK="$(e VITE_MS_REPORTES_ABC_CAMPANA_MOCK)" \
    --build-arg VITE_MS_REPORTES_ABC_CAMPANA_USE_MOCK="$(e VITE_MS_REPORTES_ABC_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_MS_REPORTES_RESPONSYS_LINEA_REAL="$(e VITE_MS_REPORTES_RESPONSYS_LINEA_REAL)" \
    --build-arg VITE_MS_REPORTES_RESPONSYS_LINEA_MOCK="$(e VITE_MS_REPORTES_RESPONSYS_LINEA_MOCK)" \
    --build-arg VITE_MS_REPORTES_RESPONSYS_LINEA_USE_MOCK="$(e VITE_MS_REPORTES_RESPONSYS_LINEA_USE_MOCK)" \
    --build-arg VITE_MS_REPORTES_RESPONSYS_CAMPANA_REAL="$(e VITE_MS_REPORTES_RESPONSYS_CAMPANA_REAL)" \
    --build-arg VITE_MS_REPORTES_RESPONSYS_CAMPANA_MOCK="$(e VITE_MS_REPORTES_RESPONSYS_CAMPANA_MOCK)" \
    --build-arg VITE_MS_REPORTES_RESPONSYS_CAMPANA_USE_MOCK="$(e VITE_MS_REPORTES_RESPONSYS_CAMPANA_USE_MOCK)" \
    \
    --build-arg VITE_OKTA_ISSUER="$(e VITE_OKTA_ISSUER)" \
    --build-arg VITE_OKTA_CLIENT_ID="$(e VITE_OKTA_CLIENT_ID)" \
    --build-arg VITE_OKTA_REDIRECT_URI="$(e VITE_OKTA_REDIRECT_URI)" \
    \
    -t "$TAG" \
    .

echo ""
echo "Exporting image to: $TAR_FILE"
docker save -o "$TAR_FILE" "$TAG"

echo ""
echo "Done."
echo "  Image : $TAG"
echo "  File  : $(pwd)/$TAR_FILE"
